spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    initialization-mode: ALWAYS
    initialization-mode: NEVER
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console


mybatis:
  mapper-locations:
    - /mappers/*.xml

user:
  profile:
    img:
      default: https://firebasestorage.googleapis.com/v0/b/userprofile-cfdff.appspot.com/o/user%2Fdefault.png?alt=media&token=7113a54b-a2b7-48b6-ac96-4e803358bbbf

